### ISSUE TITLE
Using promises in the action

### ISSUE THREAD

**Issue by danships** [estate/alexa-router#8]
Hi,

Your library for routing Alexa requests looks great, and so far I am very enthusiastic. The code I want to integrate Alexa in uses promises. The examples I have seen directly return the response.

Would it be possible to return a Promise in the handler of an action? That promise will ultimately resolve to returning the `response` to be returned towards Alexa.

**Comment by danships** [comment]
I am sorry, I did not thoroughly check the code. I tried it and it handles promises without any issues! Thanks for a great project.

**Comment by bsiddiqui** [comment]
glad you were able to figure it out @matueranet
